version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: streamlite
      POSTGRES_PASSWORD: streamlite
      POSTGRES_DB: streamlite
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    ports: ["9000:9000", "9001:9001"]
    volumes:
    - minio_data:/data


  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file: [.env]
    depends_on: [redis, minio, db]
    volumes:
      - ./:/app


volumes:
  db_data:
  minio_data:
  